### ISSUE TITLE
more than one library with package name 'com.reactlibrary'

### ISSUE THREAD

**Issue by maheshsgr** [Kishanjvaghela/react-native-cardview#12]
In Android this issue Message is appearing

Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.reactlibrary'

**Comment by zhiyingzzhou** [comment]
+1

**Comment by justynspooner** [comment]
`com.reactlibrary` is the default name for react-native libraries. This needs to be updated to something unique for this card view library like: com.kishanjvaghela.cardView.reactNative.

You're seeing this issue because you are using another library that uses the same package name. Each library needs to have a unique package name. This can be changed in `android/src/main/AndroidManifest.xml` for the library.
